services:
  - type: web
    name: gelgroup-website
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "GEL Group"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: "https://gelgroup-website.onrender.com"
      - key: APP_KEY
        sync: false
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: fr
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        value: "gelgroup.contact@gmail.com"
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: "gelgroup.contact@gmail.com"
      - key: MAIL_FROM_NAME
        value: "GEL Group"
      - key: ADMIN_PASSWORD
        sync: false
